---
- hosts: localhost
  tasks:
    - name: Build docker image
      docker_image:
        name: jenimg                            # Name of  image
        source: build
        build:
          path: /git_files/"your_Repo._name"    
  
    - name: Tag and push to docker hub
      docker_image:
        name: jenimg 
        repository: rajdandhare/jenimg:latest   # tag for DockerHub
        push: true
        source: local
